### ISSUE TITLE
Phoneme-level detection loss에 대해서 질문 있습니다!!

### ISSUE THREAD

**Issue by brianoh12** [ncsoft/PhonMatchNet#1]
3.2 training criterion 설명 중 phoneme-level detection loss 부분에서 음성과 키워드의 음소열이 동일할 때 ground truth y가 1로 매겨진다고 하는데, 이것이 어떻게 발음이 유사한 것을 구분하는 것과 연결되는지 자세한 설명을 듣고 싶습니다..!

**Comment by LeeYongHyeok** [comment]
Hello @brianoh12,

First of all, I apologize for the delayed response. I'm sorry for not checking my email notifications, which caused the delay in my reply.

We appreciate your interest in our proposal and for submitting the issue. Our proposed loss consists of two components: utterance-level and phoneme-level loss. The utterance-level loss represents the difference between the entire audio and keyword words. For example, "hello" and "hallow" would have an utterance-level ground truth of 0, even though they may sound somewhat similar to our ears. To address this problem, we introduced the phoneme-level detection loss. For instance, "hello" is composed of [HH, **EH1**, L, OW0], while "hallow" is [HH, **AE1**, L, OW0], and the phoneme-level ground truth is provided as [1, **0**, 1, 1]. This allows us to break down words into phonemes and provide additional information to the model about different pronunciations.

If you have any further questions, please feel free to email us at [eug92@naver.com](mailto:eug92@naver.com).
