### ISSUE TITLE
Questions about Query-Text/Key-Value Speech in StackExtractor vs. Self-Attention Mention

### ISSUE THREAD

**Issue by teinhonglo** [ncsoft/PhonMatchNet#10]
Hi,

Thank you for the great work on this project! I have a question regarding the `StackExtractor` class in [model/extractor.py](https://github.com/ncsoft/PhonMatchNet/blob/main/model/extractor.py). Both the paper and the code comments mention that `StackExtractor` is based on self-attention, but the `call` method's comment states:

```
* Query - text, Key, Value - speech *
```

This seems to contradict the usual self-attention setup, where query, key, and value would typically come from the same source. Could you clarify if this is intentional (perhaps for some specialized attention mechanism), or is this a misplacement in the comments? 

Thanks in advance!
Tien-Hong Lo

**Comment by LeeYongHyeok** [comment]
Hi @teinhonglo, It is a misplacement in the comments, as you can see from the call function, it works normally with self-attention. This is an incorrect comment that was missed while copy-pasting an existing comment in the process of writing code.
I'm sorry to cause confusion.
