### ISSUE TITLE
Doubt in making dataset

### ISSUE THREAD

**Issue by coding-dallas** [ncsoft/PhonMatchNet#3]
In libriphrase.py file, i am not understanding the below code snippet

for n_word in csv_list:
                    print(">> processing : {} ".format(n_word))
                    df = pd.read_csv(n_word)
                    # Split train dataset to match & unmatch case
                    anc_pos = df[['anchor_text', 'anchor', 'anchor_text', 'anchor_dur']]
                    anc_neg = df[['anchor_text', 'anchor', 'comparison_text', 'anchor_dur', 'target', 'type']]
                    com_pos = df[['comparison_text', 'comparison', 'comparison_text', 'comparison_dur']]
                    com_neg = df[['comparison_text', 'comparison', 'anchor_text', 'comparison_dur', 'target', 'type']]
                    anc_pos.columns = ['wav_label', 'anchor', 'anchor_text', 'anchor_dur']
                    com_pos.columns = ['wav_label', 'comparison', 'comparison_text', 'comparison_dur']
                    anc_pos['label'] = 1
                    anc_pos['type'] = df['type']
                    com_pos['label'] = 1
                    com_pos['type'] = df['type']

the above code part is used to making the data sample s for training. I am not understanding why the data samples are prepared in such a way. can someone help me on that

**Comment by LeeYongHyeok** [comment]
Hi, @coding-dallas
The code is a script for generating a training dataset for the files created after running the `run.sh` in the LibriPhrase repository.
For the CSV results of LibriPhrase, please check this link (https://github.com/gusrud1103/LibriPhrase).
