### ISSUE TITLE
Train with self training data

### ISSUE THREAD

**Issue by Alexi2Cat** [ncsoft/PhonMatchNet#9]
Would it be possible to train the model with my training data? If so, due to dockerization, is unclear what should it be the data preprocessing to do so. I would appreciate some help.

**Comment by LeeYongHyeok** [comment]
Hi @Alexi2Cat, Of course! If you want to train with your custom data, you can prepare positive and negative pairs by referring to the code below.
https://github.com/ncsoft/PhonMatchNet/blob/cc694ef45d85d1ba264d303c503791e8b03812cf/dataset/libriphrase.py#L86
